#!/usr/bin/env python3
"""把 agents/*.md（Claude Code 的 agent 格式）轉成 Codex 的 custom agent .toml。

用法：
  python3 scripts/gen-codex-agents.py [--out <輸出資料夾>] [--skills-root <路徑> ...] [--check]

  --out          輸出資料夾，預設 ~/.codex/agents
  --skills-root  找其他 skill 的位置，可給多次，依給的順序找；支援萬用字元。
                 給了就只找這些；不給就依序找 ~/.agents/skills、~/.codex/skills、
                 ~/.codex/plugins/cache/*/*/*/skills（Codex plugin 快取）
  --agents-dir   agent 原稿資料夾，預設本 repo 的 agents/
  --check        只列出會產生哪些檔、各自解析到的路徑與警告，不寫檔

轉換規則：
  - name、description 照抄；developer_instructions ＝ frontmatter 之後的本文
  - tools 只有 Read／Grep／Glob → sandbox_mode = "read-only"
  - tools 含 Bash → sandbox_mode = "workspace-write"（要跑 build／trace 工具、會寫快取），
    並在 developer_instructions 開頭加一句唯讀提醒——Codex 沒有逐工具白名單，只能靠這句話
  - 其他工具組合（Write、Edit…）不猜，直接報錯，要先改這支腳本決定怎麼對應
  - 本文裡的 ~/.claude/skills/<skill 名稱> 換成在 Codex 上找到的實際位置；
    找不到就換成「<找不到 <skill 名稱>：請先安裝>」並警告，但不讓整支失敗
  - 只覆寫第一行有本工具標記的 .toml；沒標記的同名檔（使用者自己寫的）跳過並警告

結束碼：0＝成功（可能有警告）；1＝有 agent 原稿格式錯誤，那幾個沒產生。
只用標準函式庫，Python 3.9 可跑。
"""
import argparse
import glob
import json
import os
import re
import sys

MARKER = "# generated by ios-dev-skill gen-codex-agents.py"

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_AGENTS_DIR = os.path.join(REPO_ROOT, "agents")
DEFAULT_OUT = "~/.codex/agents"
DEFAULT_SKILLS_ROOTS = [
    "~/.agents/skills",
    "~/.codex/skills",
    "~/.codex/plugins/cache/*/*/*/skills",
]

READ_ONLY_TOOLS = {"Read", "Grep", "Glob"}
SHELL_TOOLS = {"Bash"}
BASH_PREAMBLE = "你是唯讀審查 agent：可以執行指令收集資訊，但不准修改專案檔案。"

# ~/.claude/skills/<skill 名稱>；名稱只收 skill 目錄常見的字元，句尾標點不會被吃進去
CLAUDE_SKILL_REF = re.compile(r"~/\.claude/skills/([A-Za-z0-9_-]+)")
# 改寫完還留著的 ~/.claude/ 路徑（不是 skill 引用）：Codex 上一樣不存在，要提醒
LEFTOVER_CLAUDE_PATH = re.compile(r"(~|\$HOME|\$\{HOME\})/\.claude/")
SAFE_NAME = re.compile(r"^[A-Za-z0-9_-]+$")
GLOB_CHARS = re.compile(r"[*?\[]")


class AgentError(Exception):
    """agent 原稿格式不對；該 agent 不產生，整支結束碼為 1。"""


# ---------------------------------------------------------------- frontmatter


def _unquote(value, key, source):
    if value.startswith('"'):
        if not value.endswith('"') or len(value) < 2:
            raise AgentError(f"{source}：{key} 的雙引號沒有收尾")
        try:
            return json.loads(value)  # YAML 雙引號字串的常見跳脫和 JSON 相同
        except ValueError:
            raise AgentError(f"{source}：{key} 的雙引號字串無法解析")
    if value.startswith("'"):
        if not value.endswith("'") or len(value) < 2:
            raise AgentError(f"{source}：{key} 的單引號沒有收尾")
        return value[1:-1].replace("''", "'")
    return value


def parse_agent(text, source):
    """回傳 (frontmatter dict, 本文)。只處理這個 repo 用得到的 YAML 子集：單行的 key: value。"""
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise AgentError(f"{source}：開頭沒有 YAML frontmatter（---）")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise AgentError(f"{source}：frontmatter 沒有結尾的 ---")

    meta = {}
    for raw in lines[1:end]:
        line = raw.rstrip("\r\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[0] in " \t-":
            raise AgentError(f"{source}：frontmatter 有多行值（{line.strip()[:30]}…），本工具只支援單行的 key: value")
        key, sep, value = line.partition(":")
        if not sep:
            raise AgentError(f"{source}：frontmatter 這行看不懂：{line[:40]}")
        key, value = key.strip(), value.strip()
        if value in ("|", ">", "|-", ">-", "|+", ">+"):
            raise AgentError(f"{source}：{key} 用了多行區塊寫法，本工具只支援單行值")
        meta[key] = _unquote(value, key, source)

    body = "".join(lines[end + 1:]).lstrip("\r\n")
    return meta, body


def parse_tools(value, source):
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        value = value[1:-1]
    tools = [t.strip().strip("'\"") for t in value.split(",")]
    tools = [t for t in tools if t]
    if not tools:
        raise AgentError(f"{source}：tools 是空的")
    return tools


def sandbox_for(tools, source):
    """(sandbox_mode, 是否加唯讀提醒)。對不上兩種已知組合就報錯，不猜。"""
    tool_set = set(tools)
    if tool_set <= READ_ONLY_TOOLS:
        return "read-only", False
    if tool_set & SHELL_TOOLS and tool_set <= READ_ONLY_TOOLS | SHELL_TOOLS:
        return "workspace-write", True
    unknown = sorted(tool_set - READ_ONLY_TOOLS - SHELL_TOOLS)
    raise AgentError(
        f"{source}：tools 含本工具不知道怎麼對應到 Codex 的項目（{', '.join(unknown)}）；"
        "請先在 gen-codex-agents.py 決定它該用哪種 sandbox_mode")


# ---------------------------------------------------------------- skill 路徑


def _display_path(path, spec):
    """spec 以 ~ 開頭就把結果寫回 ~ 形式；否則用絕對路徑。"""
    path = os.path.normpath(path)
    if spec.startswith("~"):
        home = os.path.normpath(os.path.expanduser("~"))
        if path == home:
            return "~"
        if path.startswith(home + os.sep):
            return "~" + path[len(home):]
    return path


def _natural_key(text):
    return [(0, int(p), "") if p.isdigit() else (1, 0, p) for p in re.split(r"(\d+)", text) if p]


def _sort_glob_matches(matches):
    """plugin 之間照字母順序；同一個 plugin 快取有多個版本時（.../<plugin>/<版本>/skills），新版排前面。"""
    groups = {}
    for path in matches:
        path = os.path.normpath(path)
        head, last = os.path.split(path)
        plugin_dir, version = os.path.split(head) if last == "skills" else (path, "")
        groups.setdefault(plugin_dir, []).append((version, path))
    ordered = []
    for plugin_dir in sorted(groups):
        versions = sorted(groups[plugin_dir], key=lambda vp: _natural_key(vp[0]), reverse=True)
        ordered.extend(path for _, path in versions)
    return ordered


def expand_skills_roots(specs):
    """把 --skills-root（可含 ~ 與萬用字元）展開成 [(實際路徑, 顯示路徑)]，依序、去重、只留存在的資料夾。"""
    roots, seen = [], set()
    for spec in specs:
        expanded = os.path.expanduser(spec)
        if not spec.startswith("~"):
            expanded = os.path.abspath(expanded)
        if GLOB_CHARS.search(expanded):
            candidates = _sort_glob_matches(glob.glob(expanded))
        else:
            candidates = [expanded]
        for path in candidates:
            real = os.path.normpath(path)
            if real in seen or not os.path.isdir(real):
                continue
            seen.add(real)
            roots.append((real, _display_path(real, spec)))
    return roots


def find_skill(name, roots):
    for real, display in roots:
        if os.path.isfile(os.path.join(real, name, "SKILL.md")):
            return display.rstrip("/") + "/" + name
    return None


def placeholder(name):
    return f"<找不到 {name}：請先安裝>"


def rewrite_skill_paths(body, roots):
    """回傳 (改寫後本文, {skill 名稱: 解析到的路徑或 None})。"""
    resolved = {}

    def sub(match):
        name = match.group(1)
        if name not in resolved:
            resolved[name] = find_skill(name, roots)
        return resolved[name] or placeholder(name)

    return CLAUDE_SKILL_REF.sub(sub, body), resolved


# ---------------------------------------------------------------- TOML


def toml_string(value):
    """JSON 字串的跳脫規則是 TOML basic string 的子集，直接借用，不自己拼。"""
    return json.dumps(value, ensure_ascii=False)


def render_toml(agent_name, source_rel, description, sandbox_mode, instructions):
    lines = [
        MARKER,
        f"# 來源：{source_rel}。不要手改這個檔；改原稿後重跑 scripts/gen-codex-agents.py",
        f"name = {toml_string(agent_name)}",
        f"description = {toml_string(description)}",
        f"sandbox_mode = {toml_string(sandbox_mode)}",
        f"developer_instructions = {toml_string(instructions)}",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- 主流程


def convert(path, roots):
    """讀一個 agent 原稿，回傳轉換結果 dict；格式錯誤丟 AgentError。"""
    source = os.path.basename(path)
    with open(path, encoding="utf-8") as fh:
        meta, body = parse_agent(fh.read(), source)
    for key in ("name", "description", "tools"):
        if not meta.get(key, "").strip():
            raise AgentError(f"{source}：frontmatter 缺 {key}")
    name = meta["name"].strip()
    if not SAFE_NAME.match(name):
        raise AgentError(f"{source}：name「{name}」不能當檔名（只允許英數、- 與 _）")
    sandbox_mode, add_preamble = sandbox_for(parse_tools(meta["tools"], source), source)

    body, resolved = rewrite_skill_paths(body, roots)
    warnings = [f"{name}：找不到 skill「{s}」，已換成佔位字；請先安裝"
                for s, p in resolved.items() if p is None]
    leftovers = sorted({m.group(0) for m in LEFTOVER_CLAUDE_PATH.finditer(body)})
    if leftovers:
        warnings.append(f"{name}：本文還有不是 skill 引用的 Claude 路徑（{', '.join(leftovers)}），Codex 上不存在")

    instructions = BASH_PREAMBLE + "\n\n" + body if add_preamble else body
    return {
        "name": name,
        "source": source,
        "sandbox_mode": sandbox_mode,
        "resolved": resolved,
        "warnings": warnings,
        "content": render_toml(name, "agents/" + source, meta["description"].strip(),
                               sandbox_mode, instructions),
    }


def plan_write(target, content):
    """回傳 (動作, 警告或 None)。動作：新增／覆寫／不變／跳過。"""
    if not os.path.exists(target):
        return "新增", None
    try:
        with open(target, encoding="utf-8") as fh:
            existing = fh.read()
    except (OSError, UnicodeDecodeError):
        existing = ""
    if not existing.startswith(MARKER):
        return "跳過", f"{os.path.basename(target)} 已存在但不是本工具產生的（第一行沒有標記），不覆寫"
    if existing == content:
        return "不變", None
    return "覆寫", None


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="把 agents/*.md 轉成 Codex custom agent 的 .toml")
    parser.add_argument("--out", default=DEFAULT_OUT, help="輸出資料夾（預設 ~/.codex/agents）")
    parser.add_argument("--skills-root", action="append", dest="skills_roots", metavar="路徑",
                        help="找 skill 的位置，可給多次；給了就不用預設值")
    parser.add_argument("--agents-dir", default=DEFAULT_AGENTS_DIR, help="agent 原稿資料夾（預設本 repo 的 agents/）")
    parser.add_argument("--check", action="store_true", help="只列出結果，不寫檔")
    args = parser.parse_args(argv)

    out_dir = os.path.abspath(os.path.expanduser(args.out))
    specs = args.skills_roots or DEFAULT_SKILLS_ROOTS
    roots = expand_skills_roots(specs)
    sources = sorted(glob.glob(os.path.join(args.agents_dir, "*.md")))

    print(f"agent 原稿：{os.path.abspath(args.agents_dir)}（{len(sources)} 個）")
    print(f"輸出資料夾：{out_dir}" + ("（--check：不寫檔）" if args.check else ""))
    print("找 skill 的位置（依序）：")
    for _, display in roots:
        print(f"  {display}")
    if not roots:
        print("  （一個都不存在）")

    warnings, errors, results = [], [], []
    for path in sources:
        try:
            results.append(convert(path, roots))
        except AgentError as exc:
            errors.append(str(exc))

    if results and not args.check:
        os.makedirs(out_dir, exist_ok=True)

    print()
    for r in results:
        target = os.path.join(out_dir, r["name"] + ".toml")
        action, warn = plan_write(target, r["content"])
        label = {"新增": "會新增", "覆寫": "會覆寫", "不變": "不變", "跳過": "跳過"}[action] if args.check else action
        print(f"[{label}] {r['name']}.toml  sandbox_mode={r['sandbox_mode']}")
        for skill, found in sorted(r["resolved"].items()):
            print(f"    {skill} → {found or '找不到'}")
        warnings.extend(r["warnings"])
        if warn:
            warnings.append(warn)
        if action in ("新增", "覆寫") and not args.check:
            tmp = target + ".tmp"
            with open(tmp, "w", encoding="utf-8") as fh:
                fh.write(r["content"])
            os.replace(tmp, target)

    if warnings:
        print(f"\n警告（{len(warnings)}）：")
        for w in warnings:
            print(f"  - {w}")
    if errors:
        print(f"\n錯誤（{len(errors)}，這些 agent 沒有產生）：", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
