#!/usr/bin/env python3
"""gen-codex-agents.py 的回歸測試。

執行：python3 scripts/test_gen_codex_agents.py
全部在暫存目錄進行（假 agent、假 skills root、假 HOME），不碰真的 ~/.codex。
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPT = os.path.join(HERE, "gen-codex-agents.py")
MARKER = "# generated by ios-dev-skill gen-codex-agents.py"

try:  # Python 3.11+ 才有；有就多驗一次真的 TOML parser，沒有就只跑下面的小型驗證
    import tomllib
except ImportError:
    tomllib = None

TOML_LINE = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*) = (".*")$')


def parse_generated_toml(text):
    """小型 TOML 驗證：除了註解，每一行都必須是 key = "..."，且值能用 json.loads 還原。"""
    values = {}
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        m = TOML_LINE.match(line)
        if not m:
            raise AssertionError(f"不是 key = \"...\" 的一行：{line[:80]!r}")
        key, raw = m.groups()
        if key in values:
            raise AssertionError(f"key 重複：{key}")
        try:
            value = json.loads(raw)
        except ValueError as exc:
            raise AssertionError(f"{key} 的值不是合法的 basic string：{exc}")
        if not isinstance(value, str):
            raise AssertionError(f"{key} 不是字串")
        values[key] = value
    return values


def agent_md(name, tools, body, description=None):
    description = description or f"{name} 的說明：唯讀稽核。"
    return f"---\nname: {name}\ndescription: {description}\ntools: {tools}\n---\n\n{body}"


class GenBase(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="gen-codex-agents-")
        self.home = os.path.join(self.tmp, "home")
        self.agents = os.path.join(self.tmp, "agents")
        self.out = os.path.join(self.tmp, "out")
        os.makedirs(self.home)
        os.makedirs(self.agents)

    def tearDown(self):
        shutil.rmtree(self.tmp)

    def write_agent(self, filename, content):
        with open(os.path.join(self.agents, filename), "w", encoding="utf-8") as fh:
            fh.write(content)

    def make_skill(self, root, name):
        d = os.path.join(root, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "SKILL.md"), "w", encoding="utf-8") as fh:
            fh.write(f"---\nname: {name}\n---\n")
        return d

    def run_gen(self, *extra, check=False):
        args = [sys.executable, SCRIPT, "--agents-dir", self.agents, "--out", self.out, *extra]
        if check:
            args.append("--check")
        env = dict(os.environ, HOME=self.home)
        return subprocess.run(args, capture_output=True, text=True, env=env)

    def read_out(self, name):
        with open(os.path.join(self.out, name + ".toml"), encoding="utf-8") as fh:
            return fh.read()

    def generated(self, name):
        text = self.read_out(name)
        self.assertTrue(text.startswith(MARKER + "\n"), text[:80])
        values = parse_generated_toml(text)
        if tomllib is not None:
            self.assertEqual(tomllib.loads(text), values)
        return values


class Sandbox(GenBase):
    def test_read_only_tools(self):
        self.write_agent("reviewer.md", agent_md("reviewer", "Read, Grep, Glob", "只讀。\n"))
        p = self.run_gen("--skills-root", os.path.join(self.tmp, "none"))
        self.assertEqual(p.returncode, 0, p.stderr)
        v = self.generated("reviewer")
        self.assertEqual(v["sandbox_mode"], "read-only")
        self.assertEqual(v["developer_instructions"], "只讀。\n")
        self.assertEqual(v["name"], "reviewer")
        self.assertEqual(v["description"], "reviewer 的說明：唯讀稽核。")

    def test_subset_of_read_only_tools(self):
        self.write_agent("a.md", agent_md("a", "Read", "x"))
        self.assertEqual(self.run_gen().returncode, 0)
        self.assertEqual(self.generated("a")["sandbox_mode"], "read-only")

    def test_bash_means_workspace_write_with_preamble(self):
        self.write_agent("tracer.md", agent_md("tracer", "Read, Grep, Glob, Bash", "跑 trace。\n"))
        p = self.run_gen()
        self.assertEqual(p.returncode, 0, p.stderr)
        v = self.generated("tracer")
        self.assertEqual(v["sandbox_mode"], "workspace-write")
        self.assertTrue(v["developer_instructions"].startswith(
            "你是唯讀審查 agent：可以執行指令收集資訊，但不准修改專案檔案。\n\n"))
        self.assertTrue(v["developer_instructions"].endswith("跑 trace。\n"))

    def test_read_only_agent_has_no_preamble(self):
        self.write_agent("r.md", agent_md("r", "Read, Grep", "本文"))
        self.run_gen()
        self.assertNotIn("唯讀審查 agent", self.generated("r")["developer_instructions"])

    def test_flow_list_tools(self):
        self.write_agent("f.md", agent_md("f", "[Read, Bash]", "x"))
        self.assertEqual(self.run_gen().returncode, 0)
        self.assertEqual(self.generated("f")["sandbox_mode"], "workspace-write")

    def test_unknown_tools_are_an_error_not_a_guess(self):
        self.write_agent("w.md", agent_md("w", "Read, Write, Edit", "x"))
        self.write_agent("ok.md", agent_md("ok", "Read", "x"))
        p = self.run_gen()
        self.assertEqual(p.returncode, 1)
        self.assertIn("Write", p.stderr)
        self.assertFalse(os.path.exists(os.path.join(self.out, "w.toml")))
        self.assertTrue(os.path.exists(os.path.join(self.out, "ok.toml")), "其他 agent 照樣產生")

    def test_missing_frontmatter_field_is_an_error(self):
        self.write_agent("n.md", "---\nname: n\ntools: Read\n---\nbody")
        p = self.run_gen()
        self.assertEqual(p.returncode, 1)
        self.assertIn("description", p.stderr)


class SkillPaths(GenBase):
    BODY = ("1. `~/.claude/skills/alpha/SKILL.md` — 讀這個\n"
            "2. `~/.claude/skills/beta/references/x.md`\n"
            "3. 再讀一次 `~/.claude/skills/alpha/references/y.md`\n"
            "python3 ~/.claude/skills/gamma/scripts/run.py\n")

    def test_found_in_explicit_root_uses_absolute_path(self):
        root = os.path.join(self.tmp, "roots", "one")
        self.make_skill(root, "alpha")
        self.make_skill(root, "beta")
        self.make_skill(root, "gamma")
        self.write_agent("a.md", agent_md("a", "Read", self.BODY))
        p = self.run_gen("--skills-root", root)
        self.assertEqual(p.returncode, 0, p.stderr)
        body = self.generated("a")["developer_instructions"]
        self.assertIn(f"`{root}/alpha/SKILL.md`", body)
        self.assertIn(f"`{root}/beta/references/x.md`", body)
        self.assertIn(f"`{root}/alpha/references/y.md`", body)
        self.assertIn(f"python3 {root}/gamma/scripts/run.py", body)
        self.assertNotIn("~/.claude", body)
        self.assertNotIn("警告", p.stdout)

    def test_roots_are_searched_in_order(self):
        first = os.path.join(self.tmp, "first")
        second = os.path.join(self.tmp, "second")
        self.make_skill(first, "alpha")
        self.make_skill(second, "alpha")
        self.make_skill(second, "beta")
        self.write_agent("a.md", agent_md("a", "Read", "`~/.claude/skills/alpha/SKILL.md` `~/.claude/skills/beta/SKILL.md`"))
        self.run_gen("--skills-root", first, "--skills-root", second)
        body = self.generated("a")["developer_instructions"]
        self.assertIn(f"{first}/alpha/SKILL.md", body)
        self.assertIn(f"{second}/beta/SKILL.md", body)

    def test_directory_without_skill_md_does_not_count(self):
        root = os.path.join(self.tmp, "r")
        os.makedirs(os.path.join(root, "alpha"))
        self.write_agent("a.md", agent_md("a", "Read", "`~/.claude/skills/alpha/SKILL.md`"))
        self.run_gen("--skills-root", root)
        self.assertIn("<找不到 alpha：請先安裝>/SKILL.md", self.generated("a")["developer_instructions"])

    def test_not_found_becomes_placeholder_and_warns_but_succeeds(self):
        root = os.path.join(self.tmp, "r")
        self.make_skill(root, "alpha")
        self.write_agent("a.md", agent_md("a", "Read", self.BODY))
        p = self.run_gen("--skills-root", root)
        self.assertEqual(p.returncode, 0, p.stderr)
        body = self.generated("a")["developer_instructions"]
        self.assertIn("`<找不到 beta：請先安裝>/references/x.md`", body)
        self.assertIn("python3 <找不到 gamma：請先安裝>/scripts/run.py", body)
        self.assertIn(f"{root}/alpha/SKILL.md", body)
        self.assertIn("找不到 skill「beta」", p.stdout)
        self.assertIn("找不到 skill「gamma」", p.stdout)
        self.assertNotIn("找不到 skill「alpha」", p.stdout)

    def test_default_roots_keep_tilde(self):
        self.make_skill(os.path.join(self.home, ".agents", "skills"), "alpha")
        self.make_skill(os.path.join(self.home, ".codex", "skills"), "beta")
        self.write_agent("a.md", agent_md("a", "Read", "`~/.claude/skills/alpha/SKILL.md` `~/.claude/skills/beta/SKILL.md`"))
        p = self.run_gen()
        self.assertEqual(p.returncode, 0, p.stderr)
        body = self.generated("a")["developer_instructions"]
        self.assertIn("`~/.agents/skills/alpha/SKILL.md`", body)
        self.assertIn("`~/.codex/skills/beta/SKILL.md`", body)
        self.assertNotIn(self.home, body)

    def test_agents_skills_wins_over_codex_skills(self):
        self.make_skill(os.path.join(self.home, ".agents", "skills"), "alpha")
        self.make_skill(os.path.join(self.home, ".codex", "skills"), "alpha")
        self.write_agent("a.md", agent_md("a", "Read", "`~/.claude/skills/alpha/SKILL.md`"))
        self.run_gen()
        self.assertIn("~/.agents/skills/alpha/", self.generated("a")["developer_instructions"])

    def test_plugin_cache_layout(self):
        """Codex plugin 快取：~/.codex/plugins/cache/<marketplace>/<plugin>/<版本>/skills/<skill>。"""
        cache = os.path.join(self.home, ".codex", "plugins", "cache", "openai-curated", "build-ios-apps")
        self.make_skill(os.path.join(cache, "1.9.0", "skills"), "swiftui-performance-audit")
        self.make_skill(os.path.join(cache, "1.10.0", "skills"), "swiftui-performance-audit")
        self.write_agent("p.md", agent_md("p", "Read", "讀 `~/.claude/skills/swiftui-performance-audit/SKILL.md`"))
        p = self.run_gen()
        self.assertEqual(p.returncode, 0, p.stderr)
        body = self.generated("p")["developer_instructions"]
        self.assertIn("`~/.codex/plugins/cache/openai-curated/build-ios-apps/1.10.0/skills/"
                      "swiftui-performance-audit/SKILL.md`", body, "新版本優先（1.10.0 > 1.9.0）")

    def test_explicit_glob_root(self):
        base = os.path.join(self.tmp, "cache", "mk", "plug", "2.0.0", "skills")
        self.make_skill(base, "alpha")
        self.write_agent("a.md", agent_md("a", "Read", "`~/.claude/skills/alpha/SKILL.md`"))
        self.run_gen("--skills-root", os.path.join(self.tmp, "cache", "*", "*", "*", "skills"))
        self.assertIn(f"{base}/alpha/SKILL.md", self.generated("a")["developer_instructions"])

    def test_leftover_claude_path_is_warned(self):
        self.write_agent("a.md", agent_md("a", "Read", "設定在 ~/.claude/settings.json"))
        p = self.run_gen()
        self.assertEqual(p.returncode, 0)
        self.assertIn("~/.claude/", p.stdout)


class Escaping(GenBase):
    NASTY = ('他說 "不要改" 然後 C:\\Users\\x\\n 不是換行\n'
             "三個單引號 ''' 與三個雙引號 \"\"\" 都要能還原\n"
             "tab\t與中文：繁體測試　全形空白\n"
             "結尾反斜線 \\\n")

    def test_body_round_trips(self):
        self.write_agent("e.md", agent_md("e", "Read", self.NASTY))
        p = self.run_gen()
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertEqual(self.generated("e")["developer_instructions"], self.NASTY)

    def test_description_round_trips(self):
        desc = '含 "引號" 與 \\反斜線 與 \'\'\' 與中文：冒號'
        self.write_agent("d.md", agent_md("d", "Read", "x", description=desc))
        self.run_gen()
        self.assertEqual(self.generated("d")["description"], desc)

    def test_quoted_yaml_description(self):
        self.write_agent("q.md", '---\nname: q\ndescription: "有 \\"引號\\" 的說明"\ntools: Read\n---\nx')
        self.run_gen()
        self.assertEqual(self.generated("q")["description"], '有 "引號" 的說明')

    def test_every_line_is_a_single_line_string(self):
        self.write_agent("e.md", agent_md("e", "Read, Bash", self.NASTY))
        self.run_gen()
        text = self.read_out("e")
        body_lines = [l for l in text.splitlines() if l and not l.startswith("#")]
        self.assertEqual(len(body_lines), 4, "name／description／sandbox_mode／developer_instructions 各一行")

    def test_validator_rejects_bad_toml(self):
        for bad in [
            'name = "a"\ndescription = """多行\n字串"""\n',   # 多行字串
            'name = """a"""\n',                                # 三引號
            'name = "未收尾\\"\n',                            # 跳脫掉結尾引號
            "name = 'literal'\n",                              # literal string
            'name = "a"\nname = "b"\n',                        # key 重複
            '[section]\nname = "a"\n',                         # table
        ]:
            with self.assertRaises(AssertionError, msg=bad):
                parse_generated_toml(bad)


class Overwrite(GenBase):
    def test_writes_then_unchanged_then_overwrites(self):
        self.write_agent("a.md", agent_md("a", "Read", "v1"))
        p = self.run_gen()
        self.assertIn("[新增] a.toml", p.stdout)
        p = self.run_gen()
        self.assertIn("[不變] a.toml", p.stdout)
        self.write_agent("a.md", agent_md("a", "Read", "v2"))
        p = self.run_gen()
        self.assertIn("[覆寫] a.toml", p.stdout)
        self.assertEqual(self.generated("a")["developer_instructions"], "v2")

    def test_does_not_overwrite_file_without_marker(self):
        os.makedirs(self.out)
        mine = 'name = "a"\ndescription = "使用者自己寫的"\ndeveloper_instructions = "別動我"\n'
        with open(os.path.join(self.out, "a.toml"), "w", encoding="utf-8") as fh:
            fh.write(mine)
        self.write_agent("a.md", agent_md("a", "Read", "新內容"))
        p = self.run_gen()
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertEqual(self.read_out("a"), mine)
        self.assertIn("[跳過] a.toml", p.stdout)
        self.assertIn("不是本工具產生的", p.stdout)

    def test_marker_must_be_on_the_first_line(self):
        os.makedirs(self.out)
        mine = 'name = "a"\n' + MARKER + "\n"
        with open(os.path.join(self.out, "a.toml"), "w", encoding="utf-8") as fh:
            fh.write(mine)
        self.write_agent("a.md", agent_md("a", "Read", "新內容"))
        self.run_gen()
        self.assertEqual(self.read_out("a"), mine)

    def test_other_files_in_out_dir_are_left_alone(self):
        os.makedirs(self.out)
        other = os.path.join(self.out, "someone-else.toml")
        with open(other, "w", encoding="utf-8") as fh:
            fh.write("x")
        self.write_agent("a.md", agent_md("a", "Read", "y"))
        self.run_gen()
        with open(other, encoding="utf-8") as fh:
            self.assertEqual(fh.read(), "x")


class CheckMode(GenBase):
    def test_check_writes_nothing(self):
        root = os.path.join(self.tmp, "r")
        self.make_skill(root, "alpha")
        self.write_agent("a.md", agent_md("a", "Read, Bash", "`~/.claude/skills/alpha/SKILL.md` `~/.claude/skills/zeta/SKILL.md`"))
        p = self.run_gen("--skills-root", root, check=True)
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertFalse(os.path.exists(self.out), "--check 不能建立輸出資料夾")
        self.assertIn("[會新增] a.toml", p.stdout)
        self.assertIn("sandbox_mode=workspace-write", p.stdout)
        self.assertIn(f"alpha → {root}/alpha", p.stdout)
        self.assertIn("zeta → 找不到", p.stdout)
        self.assertIn("找不到 skill「zeta」", p.stdout)

    def test_check_does_not_touch_existing_files(self):
        self.write_agent("a.md", agent_md("a", "Read", "v1"))
        self.run_gen()
        before = self.read_out("a")
        self.write_agent("a.md", agent_md("a", "Read", "v2"))
        p = self.run_gen(check=True)
        self.assertIn("[會覆寫] a.toml", p.stdout)
        self.assertEqual(self.read_out("a"), before)


if __name__ == "__main__":
    unittest.main()
